version: '3.8'

services:
  auth-service:
    build: ./service-auth
    ports:
      - "5000:5000"

  product-service:
    build: ./service-product
    ports:
      - "5001:5001"

  cart-service:
    build: ./service-cart
    ports:
      - "5002:5002"
